version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5004
    

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  
