version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_URLS=http://+:5004
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always