version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  
